name: release

on:
  push:
    tags:
      - 'v*'
jobs:
  goreleaser:
    if: success()
    runs-on: ubuntu-latest
    # https://github.com/naveensrinivasan/ghactionspermissions
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      discussions: write
      issues: write
      metadata: read
      packages: write
      pull-requests: read
      repository-projects: write
      security-events: read
      statuses: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
        GPG_USER: ${{ vars.GPG_USER }}
